import "./globals.css";
import type { Metadata } from "next";
import { Inter, Raleway } from "next/font/google";

const raleway = Raleway({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ru'>
      <body className={raleway.className}>{children}</body>
    </html>
  );
}
